{{- if .Values.ingress.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kubepulse.fullname" . }}
spec:
  hosts:
  {{- toYaml .Values.ingress.istio.hosts | nindent 2 }}
  gateways:
  {{- toYaml .Values.ingress.istio.gateways | nindent 2 }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.kubepulse.basepath }}
    route:
    - destination:
        host: {{ include "kubepulse.fullname" . }}
{{- end }}
