kubepulse:
  basepath: "/"
  message: "Hello Kubernetes!"
  logVerbosity: "kubepulse=info,tower_http=info"

replicaCount: 3

image:
  repository: quay.io/duk4s/kubepulse
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  # Native Kubernetes Ingress
  native:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: kubepulse.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  # Istio Virtual Service
  istio:
    enabled: false
    gateways: []
      # - istio-system/ingressgateway
    hosts: []
      # - kubepulse.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
